### PR TITLE
Improve headers sent in HTTP requests

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
conflicts came up

**Comment by jwodder** [comment]
@yarikoptic Conflicts resolved.

**Comment by yarikoptic** [comment]
CI isn't happy

**Comment by jwodder** [comment]
@yarikoptic We were running the "Test fetching tinuous' logs" workflow so often that the step for cloning con/tinuous-inception (which apparently isn't using an authenticated token?) failed due to exhausting rate limits.

**Pull request merged**
