### PR TITLE
mypy: Set `ignore_missing_imports = False`

### PR DESCRIPTION
**Pull request by jwodder**
Builds on #176.

### CODE REVIEW

**Comment by yarikoptic** [comment]
merge conflict came up

**Comment by jwodder** [comment]
@yarikoptic Conflicts resolved.

**Comment by yarikoptic** [comment]
CI isn't happy

**Comment by jwodder** [comment]
@yarikoptic Same problem as https://github.com/con/tinuous/pull/182#issuecomment-1804269951

**Pull request merged**
