### PR TITLE
Test against Python 3.10

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by jwodder** [comment]
It seems that Travis and Appveyor don't support Python 3.10 yet.

**Comment by jwodder** [comment]
@yarikoptic That's addressed by https://github.com/con/tinuous/pull/142.

**Comment by yarikoptic** [comment]
time to refresh this PR and get it green?

**Comment by jwodder** [comment]
@yarikoptic Tests are all green now.

**Comment by yarikoptic** [comment]
awesome, let's proceed. thank you!

**Pull request merged**
